### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by james-hu** [praneetloke/AzureStorageExplorerAndroid#19]
Hi, Is this a known issue? But my ID does not end with Hotmail.com or outlook.com

Request Id: 307dbf72-9582-4a07-8694-fdaa9dd82e00
Correlation Id: 85312f9e-baf7-48ed-b941-b4c999e4e6d8
Timestamp: 2018-10-07T15:05:29Z
Message: AADSTS50020: User account 'I removed this for privacy.
' from identity provider 'live.com' does not exist in tenant 'my.app.factory' and cannot access the application '9a2e9bbc-6de9-4b91-8899-10e8c4235cc2' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by praneetloke** [comment]
@james-hu yes, unfortunately, `live.com` addresses don't work with applications registered as AAD v1 apps. As such, only accounts registered in an AAD tenant work with the app. Registering the app as a v2 app would fix it but unfortunately, doing so would not work with the Azure Resource Manager APIs since they require scopes as URIs, and the ARM APIs don't have those available for v2 apps. I tried this when I was actively developing the app and have not gone back to check if the ARM APIs have scopes for the v2 apps. If you have any suggestions, feel free to let me know and I can investigate them this week.

**Comment by praneetloke** [comment]
I have closed this issue as there is no way to support personal Microsoft Accounts or MSA as Microsoft calls them. Please reopen this issue if you believe there is a path to support both Azure AD accounts as well as personal Microsoft accounts (live.com, MSAs etc.)
